# user action: Configure the paths and settings for the vaqcuum pipeline

paths:
  tmp_dir: "/Users/ga0034de/Desktop/test_temp"

  # Reference images
  mni: "/Users/ga0034de/Downloads/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz"
  mni_mask: "/Users/ga0034de/Downloads/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_desc-brain_mask.nii.gz"
  mni_type_res: "MNI152NLin6Asym_res-2"
  
outputs:
  output_dir: "/Users/ga0034de/Desktop/test_output"
  extracted_metrics_file: "{output_dir}/extracted_metrics.csv"

inputs:
  input_dir: "/Users/ga0034de/Desktop/test_fmriprepdset"

  # Folders like:
  # sub-01_ses-01_fmriprep...
  derivative_dir: "{input_dir}/{sub_id}_{ses_id}_fmriprep*"

# If you want to focus on specific acquisitions or tasks, you can specify them here. 
# Otherwise, leave them empty to include all
bids_filters:
  t1w:
    acquisition: "*"
  bold:
    task: "rest"
    # if multiple tasks, write them as a list
    # e.g. 
    #- task: "rest"
    #- task: "baloon"

settings:
  gm_threshold: 0.3
  dropout_percentile: 10
  mattes_bins: 64
  n_jobs: 4