# configure paths and metric settings

paths:
  input_dir: "/path/to/derivatives"
  output_dir: "/path/to/output"
  extracted_metrics_file: "{output_dir}/extracted_metrics.csv"
  tmp_dir: "/path/to/tmp"

  # leave empty to use a temporary templateflow cache
  templateflow_dir: ""

parallelization:
  n_jobs: 4

settings:
  gm_threshold: 0.3
  dropout_percentile: 10
  mattes_bins: 64

# use --bids-filter to restrict work items
